import React, { useState } from 'react';
import { 
  Building2, Plane, Compass, Coffee, ShieldCheck, MapPin, 
  Wifi, Sparkles, Clock, CheckCircle2, ChevronRight, Search, 
  ExternalLink, ArrowRight, HardDrive, Filter, AlertCircle, 
  CreditCard, Armchair, Bath, Utensils, Info, Check, CloudUpload
} from 'lucide-react';
import { AIRPORT_HUBS_DB, AirportHub, AirportTerminal, AirportLounge } from '../airportData';
import { saveCustomDocumentToDrive } from '../driveService';

interface AirportHubGuideProps {
  initialAirportIata?: string;
  driveToken?: string | null;
  onNeedGoogleSignIn?: () => void;
  onNavigateToFlights?: (iata: string) => void;
}

export const AirportHubGuide: React.FC<AirportHubGuideProps> = ({
  initialAirportIata = 'DAC',
  driveToken,
  onNeedGoogleSignIn,
  onNavigateToFlights,
}) => {
  const [selectedIata, setSelectedIata] = useState<string>(
    AIRPORT_HUBS_DB[initialAirportIata] ? initialAirportIata : 'DAC'
  );
  const [activeSubTab, setActiveSubTab] = useState<'terminals' | 'lounges' | 'flow' | 'transit'>('terminals');
  const [selectedTerminalId, setSelectedTerminalId] = useState<string>('T1');
  const [loungeCardFilter, setLoungeCardFilter] = useState<'all' | 'priority' | 'credit' | 'shower'>('all');
  const [flowDirection, setFlowDirection] = useState<'departure' | 'arrival'>('departure');
  const [searchQuery, setSearchQuery] = useState('');
  
  // Drive Export state
  const [isSavingToDrive, setIsSavingToDrive] = useState(false);
  const [driveSavedUrl, setDriveSavedUrl] = useState<string | null>(null);

  const hub: AirportHub = AIRPORT_HUBS_DB[selectedIata] || AIRPORT_HUBS_DB['DAC'];

  // Keep terminal selection valid when switching airports
  const currentTerminal: AirportTerminal = 
    hub.terminals.find((t) => t.id === selectedTerminalId) || hub.terminals[0];

  const handleSelectAirport = (iata: string) => {
    setSelectedIata(iata);
    const newHub = AIRPORT_HUBS_DB[iata];
    if (newHub && newHub.terminals.length > 0) {
      setSelectedTerminalId(newHub.terminals[0].id);
    }
  };

  // Filter lounges
  const filteredLounges = hub.lounges.filter((lounge) => {
    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      const matchName = lounge.name.toLowerCase().includes(q);
      const matchTerminal = lounge.terminal.toLowerCase().includes(q);
      const matchCards = lounge.eligibleCardsBn.some(c => c.toLowerCase().includes(q));
      if (!matchName && !matchTerminal && !matchCards) return false;
    }

    if (loungeCardFilter === 'priority') {
      return lounge.accessEligibility.some(e => e.toLowerCase().includes('priority pass') || e.toLowerCase().includes('loungekey'));
    }
    if (loungeCardFilter === 'credit') {
      return lounge.eligibleCardsBn.length > 0;
    }
    if (loungeCardFilter === 'shower') {
      return lounge.hasShower;
    }
    return true;
  });

  // Handle Save to Google Drive
  const handleSaveAirportGuideToDrive = async () => {
    if (!driveToken) {
      if (onNeedGoogleSignIn) onNeedGoogleSignIn();
      return;
    }

    setIsSavingToDrive(true);
    setDriveSavedUrl(null);

    try {
      const markdown = `# ${hub.nameBn} (${hub.iata}/${hub.icao}) - টার্মিনাল, লাউঞ্জ ও ট্রানজিট নির্দেশিকা
**দেশ ও শহর:** ${hub.city}, ${hub.country}
**সংরক্ষণ তারিখ:** ${new Date().toLocaleDateString('bn-BD', { year: 'numeric', month: 'long', day: 'numeric' })}

---

## ১. টার্মিনাল ও গেট ওভারভিউ
${hub.terminals.map(t => `### ${t.nameBn} (${t.name})
- **ব্যবহৃত এয়ারলাইন্স:** ${t.airlineUsageBn}
- **বোর্ডিং গেট:** ${t.gateRange}
- **চেক-ইন কাউন্টার:** ${t.checkInCounters}
- **ব্যাগেজ বেল্ট:** ${t.baggageBelts}
- **বিবরণ:** ${t.descriptionBn}
${t.levels.map(lvl => `  * **${lvl.levelNameBn}:** ${lvl.facilitiesBn.join(', ')}`).join('\n')}
`).join('\n')}

---

## ২. লাউঞ্জ সুবিধা ও কার্ড অ্যাক্সেস
${hub.lounges.map(l => `### ${l.name} (${l.terminal})
- **লোকেশন:** ${l.location}
- **সময়সূচী:** ${l.operatingHours}
- **প্রবেশাধিকার ও ক্রেডিট কার্ড:** ${l.eligibleCardsBn.join('; ')}
- **সুবিধাসমূহ:** ${l.amenitiesBn.join(', ')} (শাওয়ার: ${l.hasShower ? 'হ্যাঁ' : 'না'}, বুফে: ${l.hasBuffet ? 'হ্যাঁ' : 'না'})
${l.notesBn ? `- **বিশেষ টিপস:** ${l.notesBn}` : ''}
`).join('\n')}

---

## ৩. ডিপার্চার স্টেপ-বাই-স্টেপ চেকলিস্ট
${hub.departureStepsBn.map(s => `${s.stepNo}. **${s.titleBn}** [${s.recommendedTimeBeforeFlight}]: ${s.descriptionBn}`).join('\n')}

---

## ৪. গ্রাউন্ড ট্রান্সপোর্ট ও লোকাল সুবিধা
${hub.groundTransportBn.map(gt => `- **${gt.typeBn}:** আনুমানিক ভাড়া ${gt.costEstimateBn} (${gt.locationBn}) — *${gt.tipsBn}*`).join('\n')}

Generated by SkyBound Bangladesh & Global Visa Tracker.
`;

      const result = await saveCustomDocumentToDrive(
        driveToken,
        `${hub.iata}_Airport_Terminal_Guide_SkyBound.txt`,
        markdown
      );

      if (result.success) {
        setDriveSavedUrl(result.fileUrl || 'saved');
      } else {
        alert(result.error || 'গুগল ড্রাইভে সংরক্ষণ করা সম্ভব হয়নি।');
      }
    } catch (err: any) {
      alert(`ত্রুটি: ${err.message || err}`);
    } finally {
      setIsSavingToDrive(false);
    }
  };

  return (
    <div className="w-full max-w-6xl mx-auto px-3 sm:px-6 py-6 pb-24 text-slate-100 animate-fadeIn">
      {/* Header Banner */}
      <div className="bg-gradient-to-r from-slate-900 via-indigo-950/40 to-slate-900 p-5 sm:p-6 rounded-2xl border border-indigo-500/30 shadow-xl mb-6">
        <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="text-xl">{hub.flagEmoji}</span>
              <span className="px-2.5 py-0.5 rounded-full text-[11px] font-mono font-bold bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
                AIRPORT HUB & TERMINAL MAP
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-[11px] font-mono font-bold bg-emerald-500/20 text-emerald-300 border border-emerald-500/30">
                {hub.iata} / {hub.icao}
              </span>
            </div>
            <h1 className="text-xl sm:text-2xl font-bold text-white flex items-center gap-2">
              <Building2 className="w-6 h-6 text-indigo-400" />
              <span>{hub.nameBn}</span>
            </h1>
            <p className="text-xs sm:text-sm text-slate-400 mt-1 max-w-2xl">
              টার্মিনাল লেআউট, গেট ডিরেক্টরি, ব্যাংক কার্ড দিয়ে লাউঞ্জ অ্যাক্সেস, ডিপার্চার/অ্যারাইভাল চেকলিস্ট এবং লোকাল গণপরিবহন গাইড।
            </p>
          </div>

          <div className="flex flex-wrap items-center gap-2">
            <button
              onClick={handleSaveAirportGuideToDrive}
              disabled={isSavingToDrive}
              className="px-3.5 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-xs flex items-center gap-1.5 shadow-md shadow-indigo-600/30 transition-all cursor-pointer disabled:opacity-50"
            >
              <CloudUpload className="w-4 h-4" />
              <span>{isSavingToDrive ? 'ড্রাইভে সেভ হচ্ছে...' : 'গাইড Google Drive-এ সেভ'}</span>
            </button>
          </div>
        </div>

        {/* Success toast inside card */}
        {driveSavedUrl && (
          <div className="mt-3 p-2.5 rounded-xl bg-emerald-950/70 border border-emerald-500/40 text-xs text-emerald-300 flex items-center justify-between">
            <div className="flex items-center gap-2">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <span>{hub.nameBn}-এর টার্মিনাল ও লাউঞ্জ গাইড আপনার গুগল ড্রাইভে সংরক্ষিত হয়েছে!</span>
            </div>
            {driveSavedUrl !== 'saved' && (
              <a
                href={driveSavedUrl}
                target="_blank"
                rel="noreferrer"
                className="underline text-indigo-300 hover:text-white ml-2 flex items-center gap-1 font-medium"
              >
                <span>ফাইলটি খুলুন</span>
                <ExternalLink className="w-3.5 h-3.5" />
              </a>
            )}
          </div>
        )}

        {/* Airport Hub Selector Carousel */}
        <div className="mt-5 pt-4 border-t border-slate-800/80 flex items-center gap-2 overflow-x-auto pb-1 scrollbar-thin">
          <span className="text-xs text-slate-400 font-medium whitespace-nowrap mr-1 flex items-center gap-1">
            <MapPin className="w-3.5 h-3.5 text-indigo-400" />
            এয়ারপোর্ট হাব:
          </span>
          {Object.values(AIRPORT_HUBS_DB).map((airport) => (
            <button
              key={airport.iata}
              onClick={() => handleSelectAirport(airport.iata)}
              className={`px-3 py-1.5 rounded-xl text-xs font-semibold flex items-center gap-1.5 transition-all whitespace-nowrap cursor-pointer ${
                selectedIata === airport.iata
                  ? 'bg-indigo-600 text-white shadow-md shadow-indigo-600/40 border border-indigo-400/50'
                  : 'bg-slate-850 hover:bg-slate-800 text-slate-300 border border-slate-750'
              }`}
            >
              <span>{airport.flagEmoji}</span>
              <span>{airport.iata}</span>
              <span className="opacity-75 hidden sm:inline">({airport.city.split(' ')[0]})</span>
            </button>
          ))}
        </div>
      </div>

      {/* Sub-tab Navigation */}
      <div className="flex items-center gap-2 border-b border-slate-800 pb-3 mb-6 overflow-x-auto">
        <button
          onClick={() => setActiveSubTab('terminals')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer whitespace-nowrap ${
            activeSubTab === 'terminals'
              ? 'bg-indigo-600 text-white shadow-md'
              : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
          }`}
        >
          <Building2 className="w-4 h-4" />
          <span>টার্মিনাল ও গেট ম্যাপ</span>
          <span className="px-1.5 py-0.2 rounded-md bg-indigo-900/60 text-[10px] text-indigo-200">
            {hub.terminals.length}টি টার্মিনাল
          </span>
        </button>

        <button
          onClick={() => setActiveSubTab('lounges')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer whitespace-nowrap ${
            activeSubTab === 'lounges'
              ? 'bg-amber-600 text-white shadow-md'
              : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
          }`}
        >
          <Coffee className="w-4 h-4 text-amber-400" />
          <span>লাউঞ্জ ও কার্ড সুবিধা</span>
          <span className="px-1.5 py-0.2 rounded-md bg-amber-900/60 text-[10px] text-amber-200">
            {hub.lounges.length}টি লাউঞ্জ
          </span>
        </button>

        <button
          onClick={() => setActiveSubTab('flow')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer whitespace-nowrap ${
            activeSubTab === 'flow'
              ? 'bg-emerald-600 text-white shadow-md'
              : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
          }`}
        >
          <Compass className="w-4 h-4 text-emerald-400" />
          <span>প্যাসেঞ্জার ফ্লো চেকলিস্ট</span>
        </button>

        <button
          onClick={() => setActiveSubTab('transit')}
          className={`px-4 py-2 rounded-xl text-xs font-semibold flex items-center gap-2 transition-all cursor-pointer whitespace-nowrap ${
            activeSubTab === 'transit'
              ? 'bg-sky-600 text-white shadow-md'
              : 'bg-slate-900 text-slate-400 hover:text-slate-200 border border-slate-800'
          }`}
        >
          <Plane className="w-4 h-4 text-sky-400" />
          <span>ট্রান্সপোর্ট ও সার্ভিসেস</span>
        </button>
      </div>

      {/* ---------------------------------------------------- */}
      {/* 1. TERMINALS & GATES VIEW                            */}
      {/* ---------------------------------------------------- */}
      {activeSubTab === 'terminals' && (
        <div className="space-y-6">
          {/* Terminal Tabs Selector */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-2.5">
            {hub.terminals.map((t) => {
              const isSelected = t.id === currentTerminal.id;
              return (
                <button
                  key={t.id}
                  onClick={() => setSelectedTerminalId(t.id)}
                  className={`p-3 rounded-xl border text-left transition-all cursor-pointer ${
                    isSelected
                      ? 'bg-indigo-950/60 border-indigo-500 shadow-md shadow-indigo-950/50 ring-1 ring-indigo-500/50'
                      : 'bg-slate-900/80 border-slate-800 hover:border-slate-700'
                  }`}
                >
                  <div className="flex items-center justify-between mb-1">
                    <span className="font-mono font-bold text-xs text-indigo-400">{t.id}</span>
                    {t.isNewTerminal && (
                      <span className="px-1.5 py-0.5 rounded text-[9px] font-bold bg-amber-500/20 text-amber-300 border border-amber-500/40">
                        NEW FLAGSHIP
                      </span>
                    )}
                  </div>
                  <h4 className="font-bold text-xs sm:text-sm text-white line-clamp-1">{t.nameBn.split('(')[0]}</h4>
                  <p className="text-[11px] text-slate-400 font-mono mt-0.5">{t.gateRange}</p>
                </button>
              );
            })}
          </div>

          {/* Selected Terminal Card */}
          <div className="bg-slate-900 p-5 sm:p-6 rounded-2xl border border-slate-800 shadow-lg">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 pb-4 border-b border-slate-800">
              <div>
                <div className="flex items-center gap-2">
                  <h3 className="text-lg sm:text-xl font-bold text-white">
                    {currentTerminal.nameBn}
                  </h3>
                  {currentTerminal.isNewTerminal && (
                    <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-emerald-500/20 text-emerald-400 border border-emerald-500/40">
                      ★ মেগা টার্মিনাল
                    </span>
                  )}
                </div>
                <p className="text-xs text-slate-400 mt-1">{currentTerminal.descriptionBn}</p>
              </div>

              <div className="flex flex-wrap items-center gap-2">
                <span className="px-2.5 py-1 rounded-lg bg-indigo-950/70 border border-indigo-500/30 text-indigo-300 text-xs font-mono">
                  🚪 {currentTerminal.gateRange}
                </span>
              </div>
            </div>

            {/* Terminal Specifications Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3 my-4">
              <div className="bg-slate-850/80 p-3 rounded-xl border border-slate-750">
                <span className="text-slate-400 text-xs block mb-1">✈️ ব্যবহৃত এয়ারলাইন্স:</span>
                <span className="text-slate-200 text-xs font-medium leading-relaxed block">
                  {currentTerminal.airlineUsageBn}
                </span>
              </div>

              <div className="bg-slate-850/80 p-3 rounded-xl border border-slate-750">
                <span className="text-slate-400 text-xs block mb-1">🎫 চেক-ইন কাউন্টার:</span>
                <span className="text-emerald-300 text-xs font-semibold block">
                  {currentTerminal.checkInCounters}
                </span>
              </div>

              <div className="bg-slate-850/80 p-3 rounded-xl border border-slate-750">
                <span className="text-slate-400 text-xs block mb-1">🧳 আগমন লাগেজ বেল্ট:</span>
                <span className="text-sky-300 text-xs font-semibold block">
                  {currentTerminal.baggageBelts}
                </span>
              </div>
            </div>

            {/* Level by Level Facilities */}
            <div className="mt-5">
              <h4 className="text-xs font-bold text-slate-300 uppercase tracking-wider mb-3 flex items-center gap-1.5">
                <Building2 className="w-4 h-4 text-indigo-400" />
                ফ্লোর ও সুবিধা বণ্টন (Floor & Facility Distribution)
              </h4>
              <div className="space-y-3">
                {currentTerminal.levels.map((lvl, idx) => (
                  <div key={idx} className="bg-slate-950/60 p-3.5 rounded-xl border border-slate-800/80 flex flex-col sm:flex-row sm:items-start gap-3">
                    <div className="sm:w-44 shrink-0">
                      <span className="px-2 py-1 rounded-md bg-slate-800 text-indigo-300 text-xs font-bold block text-center sm:text-left">
                        {lvl.levelNameBn}
                      </span>
                    </div>
                    <div className="flex-1 flex flex-wrap gap-1.5">
                      {lvl.facilitiesBn.map((fac, fIdx) => (
                        <span key={fIdx} className="px-2.5 py-1 rounded-lg bg-slate-900 border border-slate-800 text-slate-300 text-xs flex items-center gap-1">
                          <Check className="w-3 h-3 text-emerald-400 shrink-0" />
                          <span>{fac}</span>
                        </span>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {/* ---------------------------------------------------- */}
      {/* 2. LOUNGES & CARD ACCESS VIEW                        */}
      {/* ---------------------------------------------------- */}
      {activeSubTab === 'lounges' && (
        <div className="space-y-5">
          {/* Lounge Filters & Search */}
          <div className="bg-slate-900 p-4 rounded-2xl border border-slate-800 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex flex-wrap items-center gap-1.5">
              <span className="text-xs text-slate-400 mr-1 flex items-center gap-1">
                <Filter className="w-3.5 h-3.5" /> ফিল্টার:
              </span>
              <button
                onClick={() => setLoungeCardFilter('all')}
                className={`px-3 py-1 rounded-xl text-xs font-medium transition-colors cursor-pointer ${
                  loungeCardFilter === 'all' ? 'bg-amber-600 text-white font-bold' : 'bg-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                সকল ({hub.lounges.length})
              </button>
              <button
                onClick={() => setLoungeCardFilter('priority')}
                className={`px-3 py-1 rounded-xl text-xs font-medium transition-colors cursor-pointer ${
                  loungeCardFilter === 'priority' ? 'bg-amber-600 text-white font-bold' : 'bg-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                Priority Pass
              </button>
              <button
                onClick={() => setLoungeCardFilter('credit')}
                className={`px-3 py-1 rounded-xl text-xs font-medium transition-colors cursor-pointer ${
                  loungeCardFilter === 'credit' ? 'bg-amber-600 text-white font-bold' : 'bg-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                💳 ব্যাংক ক্রেডিট কার্ড
              </button>
              <button
                onClick={() => setLoungeCardFilter('shower')}
                className={`px-3 py-1 rounded-xl text-xs font-medium transition-colors cursor-pointer ${
                  loungeCardFilter === 'shower' ? 'bg-amber-600 text-white font-bold' : 'bg-slate-800 text-slate-400 hover:text-white'
                }`}
              >
                🚿 শাওয়ার সুবিধা
              </button>
            </div>

            <div className="relative sm:w-64">
              <Search className="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="লাউঞ্জ বা কার্ডের নাম..."
                className="w-full pl-8 pr-3 py-1.5 rounded-xl bg-slate-950 border border-slate-800 text-xs text-white focus:outline-none focus:border-amber-500"
              />
            </div>
          </div>

          {/* Lounges List Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {filteredLounges.map((lounge) => (
              <div
                key={lounge.id}
                className="bg-slate-900 rounded-2xl border border-slate-800 p-5 shadow-lg flex flex-col justify-between hover:border-amber-500/30 transition-all"
              >
                <div>
                  <div className="flex items-start justify-between gap-2 mb-2">
                    <div>
                      <span className="px-2 py-0.5 rounded text-[10px] font-mono font-bold bg-amber-500/20 text-amber-300 border border-amber-500/30 inline-block mb-1">
                        {lounge.terminal}
                      </span>
                      <h3 className="text-base font-bold text-white flex items-center gap-1.5">
                        <Armchair className="w-4 h-4 text-amber-400 shrink-0" />
                        <span>{lounge.name}</span>
                      </h3>
                    </div>

                    <div className="flex items-center gap-1">
                      {lounge.hasShower && (
                        <span className="p-1 rounded bg-slate-800 text-sky-400 text-[10px] flex items-center gap-0.5" title="শাওয়ার সুবিধা আছে">
                          <Bath className="w-3 h-3" />
                        </span>
                      )}
                      {lounge.hasBuffet && (
                        <span className="p-1 rounded bg-slate-800 text-emerald-400 text-[10px] flex items-center gap-0.5" title="গরম বুফে খাবার">
                          <Utensils className="w-3 h-3" />
                        </span>
                      )}
                    </div>
                  </div>

                  <p className="text-xs text-slate-400 mb-3 flex items-center gap-1.5">
                    <MapPin className="w-3 h-3 text-slate-500 shrink-0" />
                    <span>{lounge.location}</span>
                  </p>

                  <div className="text-[11px] text-slate-400 font-mono mb-3 flex items-center gap-1.5">
                    <Clock className="w-3 h-3 text-indigo-400" />
                    <span>সময়সূচী: {lounge.operatingHours}</span>
                  </div>

                  {/* Eligible Cards */}
                  <div className="bg-slate-950/70 p-3 rounded-xl border border-slate-800 mb-3">
                    <span className="text-[11px] font-semibold text-amber-300 block mb-1.5 flex items-center gap-1">
                      <CreditCard className="w-3.5 h-3.5" />
                      যেসব কার্ডে বিনামূল্যে প্রবেশ সুবিধা:
                    </span>
                    <div className="flex flex-wrap gap-1">
                      {lounge.eligibleCardsBn.map((card, cIdx) => (
                        <span key={cIdx} className="px-2 py-0.5 rounded bg-slate-850 text-slate-200 text-[11px] border border-slate-750">
                          {card}
                        </span>
                      ))}
                    </div>
                  </div>

                  {/* Amenities */}
                  <div className="flex flex-wrap gap-1.5 mb-2">
                    {lounge.amenitiesBn.map((am, aIdx) => (
                      <span key={aIdx} className="px-2 py-0.5 rounded-md bg-slate-850/90 text-slate-300 text-[10px] border border-slate-750 flex items-center gap-1">
                        <Check className="w-2.5 h-2.5 text-emerald-400" />
                        <span>{am}</span>
                      </span>
                    ))}
                  </div>

                  {lounge.notesBn && (
                    <p className="text-[11px] text-amber-200/80 bg-amber-950/30 p-2 rounded-lg border border-amber-500/20 mt-2">
                      💡 {lounge.notesBn}
                    </p>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ---------------------------------------------------- */}
      {/* 3. STEP-BY-STEP PASSENGER FLOW VIEW                  */}
      {/* ---------------------------------------------------- */}
      {activeSubTab === 'flow' && (
        <div className="space-y-6">
          {/* Direction Toggle */}
          <div className="flex justify-center">
            <div className="bg-slate-900 p-1 rounded-2xl border border-slate-800 flex items-center">
              <button
                onClick={() => setFlowDirection('departure')}
                className={`px-5 py-2 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                  flowDirection === 'departure'
                    ? 'bg-emerald-600 text-white shadow-md shadow-emerald-950/50'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                <Plane className="w-4 h-4 rotate-45" />
                <span>🛫 প্রস্থান চেকলিস্ট (Departure Flow)</span>
              </button>

              <button
                onClick={() => setFlowDirection('arrival')}
                className={`px-5 py-2 rounded-xl text-xs font-bold flex items-center gap-1.5 transition-all cursor-pointer ${
                  flowDirection === 'arrival'
                    ? 'bg-sky-600 text-white shadow-md shadow-sky-950/50'
                    : 'text-slate-400 hover:text-white'
                }`}
              >
                <Plane className="w-4 h-4 -rotate-45" />
                <span>🛬 আগমন গাইড (Arrival Flow)</span>
              </button>
            </div>
          </div>

          {/* Flow Steps Timeline */}
          <div className="bg-slate-900 p-5 sm:p-6 rounded-2xl border border-slate-800">
            <h3 className="text-base sm:text-lg font-bold text-white mb-4 flex items-center gap-2">
              <Compass className="w-5 h-5 text-emerald-400" />
              <span>
                {flowDirection === 'departure'
                  ? `${hub.nameBn}-এ আন্তর্জাতিক প্রস্থান ধাপসমূহ`
                  : `${hub.nameBn}-এ আগমন ও ইমিগ্রেশন পারাপার`}
              </span>
            </h3>

            <div className="space-y-4">
              {(flowDirection === 'departure' ? hub.departureStepsBn : hub.arrivalStepsBn).map((step) => (
                <div
                  key={step.stepNo}
                  className="flex items-start gap-3 sm:gap-4 p-3.5 rounded-xl bg-slate-950/70 border border-slate-800/80 hover:border-slate-700 transition-colors"
                >
                  <div className="w-8 h-8 rounded-full bg-indigo-600/30 border border-indigo-500/50 text-indigo-300 font-bold text-sm flex items-center justify-center shrink-0">
                    {step.stepNo}
                  </div>

                  <div className="flex-1">
                    <div className="flex flex-wrap items-center justify-between gap-2 mb-1">
                      <h4 className="text-sm font-bold text-white">{step.titleBn}</h4>
                      {'recommendedTimeBeforeFlight' in step && (
                        <span className="px-2 py-0.5 rounded text-[10px] font-mono font-semibold bg-indigo-950 text-indigo-300 border border-indigo-500/40">
                          ⏱️ {(step as any).recommendedTimeBeforeFlight}
                        </span>
                      )}
                    </div>
                    <p className="text-xs text-slate-300 leading-relaxed">{step.descriptionBn}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* ---------------------------------------------------- */}
      {/* 4. GROUND TRANSIT & SERVICES VIEW                    */}
      {/* ---------------------------------------------------- */}
      {activeSubTab === 'transit' && (
        <div className="space-y-6">
          {/* Essential Services Grid */}
          <div>
            <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Sparkles className="w-4 h-4 text-sky-400" />
              জরুরি পরিষেবা ও কাউন্টার
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {hub.services.map((srv, idx) => (
                <div key={idx} className="bg-slate-900 p-4 rounded-xl border border-slate-800">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="px-2 py-0.5 rounded text-[10px] font-bold bg-sky-950 text-sky-300 border border-sky-500/40">
                      {srv.categoryLabelBn}
                    </span>
                    <h4 className="font-bold text-xs sm:text-sm text-white">{srv.nameBn}</h4>
                  </div>
                  <p className="text-xs text-slate-400 mb-2 flex items-center gap-1">
                    <MapPin className="w-3 h-3 text-slate-500" />
                    <span>{srv.locationBn}</span>
                  </p>
                  <p className="text-xs text-slate-300 leading-relaxed bg-slate-950/60 p-2.5 rounded-lg border border-slate-850">
                    {srv.detailsBn}
                  </p>
                </div>
              ))}
            </div>
          </div>

          {/* Ground Transportation Options */}
          <div>
            <h3 className="text-sm font-bold text-slate-200 uppercase tracking-wider mb-3 flex items-center gap-1.5">
              <Plane className="w-4 h-4 text-emerald-400" />
              শহরে যাতায়াত ও গণপরিবহন (Ground Transport)
            </h3>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
              {hub.groundTransportBn.map((gt, idx) => (
                <div key={idx} className="bg-slate-900 p-4 rounded-xl border border-slate-800 flex flex-col justify-between">
                  <div>
                    <h4 className="font-bold text-sm text-white mb-1">{gt.typeBn}</h4>
                    <div className="p-2 rounded-lg bg-emerald-950/50 border border-emerald-500/30 text-emerald-300 font-mono text-xs font-bold my-2">
                      ভাড়া: {gt.costEstimateBn}
                    </div>
                    <p className="text-xs text-slate-400 mb-2 flex items-start gap-1">
                      <MapPin className="w-3 h-3 text-slate-500 shrink-0 mt-0.5" />
                      <span>{gt.locationBn}</span>
                    </p>
                  </div>
                  <p className="text-[11px] text-slate-300 bg-slate-950 p-2 rounded-lg border border-slate-850">
                    💡 {gt.tipsBn}
                  </p>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
